name: Build

on: [
  pull_request,
  push,
  workflow_dispatch
]

jobs:
  ejecutar-tests:
    uses: agustisera1/gh-actions/.github/workflows/tests.yml@main

  buildear-proyecto:
    needs: ejecutar-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      - name: Correr unit tests
        run: npm run build
