name: Build

on: [push, pull_request]

jobs:
  ejecutar-setup:
    uses: agustisera1/gh-actions/.github/workflows/setup.yml@main

  ejecutar-tests:
    needs: ejecutar-setup
    uses: agustisera1/gh-actions/.github/workflows/tests.yml@main

  buildear-proyecto:
    needs: ejecutar-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Buildear proyecto
        run: npm run build
