name: Unit tests

on: [
  workflow_dispatch,
  pull_request
]

jobs:
  realizar-setup:
    uses: agustisera1/gh-actions/.github/workflows/setup.yml@main
  ejecutar-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Correr unit tests
        run: npm test
