name: Unit tests

on: [workflow_dispatch]

jobs:
  realizar-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Setup proyecto (reusable workflow)
        uses: agustisera1/gh-actions/.github/workflows/setup.yml@main

      - name: Correr unit tests
        run: npm test


    
