name: Unit tests

on: [
  pull_request,
  push,
  workflow_dispatch
]

jobs:
  realizar-setup:
    uses: agustisera1/gh-actions/.github/workflows/setup.yml@main

  ejecutar-tests:
    needs: realizar-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Correr unit tests
        run: npm test
