name: Unit tests

on:
  workflow_call:

jobs:
  ejecutar-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Correr unit tests
        run: npm test
